/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import java.net.HttpURLConnection;
import java.net.URL;
import java.io.OutputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import javax.swing.JOptionPane;

import org.json.JSONObject;

/**
 * 
 * @author VICTUS
 */

public class Login extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form MainFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        // Main panel with padding
        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        // Title
        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Welcome to ShopSphere");

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(6, 6, 18, 6);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel1.add(jLabel5, gbc);

        // Subtitle
        javax.swing.JLabel subtitle = new javax.swing.JLabel("Sign in to continue");
        subtitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        subtitle.setForeground(new java.awt.Color(200, 200, 200));
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(0, 6, 18, 6);
        jPanel1.add(subtitle, gbc);

        // Email label
        jLabel3.setText("Email");
        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jLabel3.setForeground(new java.awt.Color(230, 230, 230));
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.insets = new java.awt.Insets(4, 6, 4, 6);
        jPanel1.add(jLabel3, gbc);

        // Email field
        Email.setColumns(24);
        Email.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        Email.setBackground(new java.awt.Color(10, 10, 10));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8));
        Email.setToolTipText("Enter your account email");
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.insets = new java.awt.Insets(4, 6, 4, 6);
        jPanel1.add(Email, gbc);

        // Password label
        jLabel4.setText("Password");
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jLabel4.setForeground(new java.awt.Color(230, 230, 230));
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.insets = new java.awt.Insets(4, 6, 4, 6);
        jPanel1.add(jLabel4, gbc);

        // Password field
        Password.setColumns(24);
        Password.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        Password.setBackground(new java.awt.Color(10, 10, 10));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8));
        Password.setToolTipText("Enter your password");
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.insets = new java.awt.Insets(4, 6, 4, 6);
        jPanel1.add(Password, gbc);

        // 'Remember me' removed; kept only the New user? label

        javax.swing.JLabel newUser = new javax.swing.JLabel("New user?");
        newUser.setForeground(new java.awt.Color(180, 180, 255));
        newUser.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        newUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newUser.setToolTipText("Create a new account");
        newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                // Open register form
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Register().setVisible(true);
                    }
                });
                Login.this.dispose();
            }
        });
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = java.awt.GridBagConstraints.EAST;
        gbc.insets = new java.awt.Insets(8, 6, 8, 6);
        jPanel1.add(newUser, gbc);

        // Login button (prominent)
        Login.setText("Sign in");
        Login.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        Login.setPreferredSize(new java.awt.Dimension(140, 36));
        Login.setToolTipText("Sign in to your account");
        // Wire the login button to the action handler
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(12, 6, 6, 6);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel1.add(Login, gbc);

        // Former small Register button removed - use 'New user?' label instead

        // Accessibility/tooling
        Email.getAccessibleContext().setAccessibleName("Email");
        Email.getAccessibleContext().setAccessibleDescription("User email");
        Password.getAccessibleContext().setAccessibleName("Password");
        Password.getAccessibleContext().setAccessibleDescription("User password");

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** **/

    public Login() {
        initComponents(); // NetBeans GUI code, DO NOT remove

        System.out.println("Register constructor called!");

        setSize(1000, 700); // optional: enforce frame size
        setLocationRelativeTo(null); // center frame

        // clear default placeholders

        Email.setText("");
        Password.setText("");

        setVisible(true); // make frame visible
    }

    private boolean loginUser(String email, String password) {
        System.out.println("Inside Login");
        System.out.println("Email: " + email + ", Password: " + password);
        try {
            URL url = new URL("http://localhost:8080/auth/login");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setDoOutput(true);

            JSONObject json = new JSONObject();

            json.put("email", email);
            json.put("password", password);
            try (OutputStream os = conn.getOutputStream()) {
                os.write(json.toString().getBytes());
            }

            int responseCode = conn.getResponseCode();
            BufferedReader in = null;
            InputStreamReader isr = null;

            if (responseCode >= 200 && responseCode < 300) {
                isr = new InputStreamReader(conn.getInputStream());
            } else if (conn.getErrorStream() != null) {
                isr = new InputStreamReader(conn.getErrorStream());
            }

            if (isr != null) {
                in = new BufferedReader(isr);
                String inputLine;
                StringBuilder response = new StringBuilder();
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                in.close();

                JSONObject resp = new JSONObject(response.toString());
                if ("success".equals(resp.getString("status"))) {
                    AuthManager.Token = resp.getString("accessToken");
                    AuthManager.Refresh = resp.getString("refreshToken");
                    System.out.print("Token:" + AuthManager.Token);
                    return (true);
                }

                System.out.println("Response: " + response);
            } else {
                System.out.println("No response body from server");
            }

            return (responseCode == 200 || responseCode == 201);

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginActionPerformed

        String email = Email.getText();
        String password = new String(Password.getPassword());

        System.out.println("Email: " + email);
        System.out.println("Password: " + password);

        boolean success = loginUser(email, password);
        if (success) {
            JOptionPane.showMessageDialog(this, "Logged In");
            MainFrame main = new MainFrame();
            main.setVisible(true);
            this.dispose();

            // new HomePage().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password");
        }
    }// GEN-LAST:event_LoginActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EmailActionPerformed

    // Register action removed; 'New user?' label opens the Register frame instead.

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Theme.applyDarkTheme();
            new Login();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
